package org.denevell.natch.jerseymvc.app.template;

import java.beans.Introspector;
import java.beans.PropertyDescriptor;
import java.io.StringWriter;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.reflect.Method;
import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;

import org.glassfish.jersey.client.JerseyClient;
import org.glassfish.jersey.client.JerseyClientBuilder;
import org.glassfish.jersey.jackson.JacksonFeature;

import com.github.mustachejava.DefaultMustacheFactory;

public class TemplateModule {
	
	protected StringWriter writer;
	protected HttpServletRequest mRequest;
	private String mTemplateFile;
	protected static DefaultMustacheFactory sFactory = new DefaultMustacheFactory();
	protected static JerseyClient sService = JerseyClientBuilder.createClient().register(JacksonFeature.class);

    @Target(ElementType.FIELD)
    @Retention(RetentionPolicy.RUNTIME)
    public static @interface TemplateModuleInfo {
	    String value();
	    /**
	     * If it is used in GET, the previous value for this module, 
	     * perhaps generated by the POST, would need to be 
	     * overwritten, since that may have not set up the module
	     * correctly.
	     */
	    boolean usedInGET() default false;
    }

    @Target(ElementType.TYPE)
    @Retention(RetentionPolicy.RUNTIME)
    public static @interface TemplateName {
	    String value();
    }

	public TemplateModule(String templateFile) {
		mTemplateFile = templateFile;
		writer = new StringWriter();
	}
	
	protected String createTemplate(String templateName, Object object) {
    	sFactory
    		.compile(templateName)
    		.execute(writer,object);
		writer.flush();
		return writer.toString();
	}

	public String template(final HttpServletRequest request) throws Exception {
		if(mTemplateFile==null) return "";
		mRequest = request;
		modifyTemplateDataBeforeRender(request);
		HashMap<String, Object> hm = new HashMap<>();
		for(PropertyDescriptor propertyDescriptor : 
		    Introspector.getBeanInfo(getClass(), Object.class).getPropertyDescriptors()){
		    Method readMethod = propertyDescriptor.getReadMethod();
		    String property = readMethod.getName().substring(3).toLowerCase();
			//System.out.println("#: " + property);
			hm.put(property, readMethod.invoke(this));
		}
		return createTemplate(mTemplateFile, hm);
	}

	protected void modifyTemplateDataBeforeRender(HttpServletRequest request) {
		
	}

}
